// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: ulpcdqmirdrncotqjqum

class SupabaseConfig {
  static const String supabaseUrl = 'https://ulpcdqmirdrncotqjqum.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVscGNkcW1pcmRybmNvdHFqcXVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwNDUwNDUsImV4cCI6MjA3OTYyMTA0NX0.tLSR3dCOaCn7I4bNQLN0IaEjZO1C3psLTQx1ayMvgR8';
}
